{% set name = "rtopy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 05ab6cf5d40a6b367492acdf5e46d0a5c33cd02d43e74d4ffcbb28df37a3f659

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - matplotlib-base
    - numpy >=1.14.0
    - scipy >=0.19.0
    - Click 
  run:
    - python
    - scipy >=0.19.0
    - matplotlib-base
    - Click 

test:
  imports: rtopy

about:
  home: https://techtonique.github.io/rtopy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Call R functions from Python
  description: Call R functions from Python
  doc_url: https://techtonique.github.io/rtopy/
  dev_url: https://github.com/Techtonique/rtopy

extra:
  recipe-maintainers:
    - thierrymoudiki
